name: Publish to Docker Hub

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push (release)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/github-actions-self-hosted-runner:${{ github.event.release.tag_name }}, ghcr.io/${{ github.actor }}/github-actions-self-hosted-runner:latest

      - name: Build and push (manual)
        if: github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.actor }}/github-actions-self-hosted-runner:latest
